- .github/workflows/ci.yml
- setup.py
- src/vector/awkward/lorentz/xyzt.py
- src/vector/numba/awkward/lorentz/xyzt.py
- tests/awkward_tests/__init__.py
- tests/awkward_tests/test_demo.py
- tests/conftest.py
- tests/numba_tests/test_awkward.py
Since awkward 1.0.0 has been released, changing `awkward1` &rarr; `awkward`.
Without these changes any code using both awkward1 (e.g. from `vector`) and awkward 1.0 will crash.
Also updated the pytest fixture for the new syntax since the last awkward1 change.
> awkward1 to awkward

- .github/workflows/ci.yml
- setup.cfg
- setup.py
- src/vector/compute/spatial/costheta.py
- src/vector/compute/spatial/cottheta.py
- src/vector/compute/spatial/eta.py
- src/vector/compute/spatial/z.py
- tests/test_compute_features.py
This adds a static analysis of all the `compute` functions to be sure that no one adds unsupported language features. Those functions have to be the least-common denominator to work in all the backends: NumExpr, Numba, JAX, etc.
Note: to avoid this long-running test (which only happens if you have uncompyle6 installed), you say "`not slow`".
```bash
python -m pytest tests -m "not slow"
```
> Constrain the allowed set of language features in 'compute' functions.

- setup.py
- src/vector/backends/numba_.py
- src/vector/backends/numba_object.py
Not having to copy all the `compute` functions (to have a pure Python version and a CPUDispatcher version) lets us relax the minimum Python version for Numba support because copying the functions also required the creation of a `CellType`, which is only provided by Python 3.8+ and my work-around only worked in Python 3.7+.
> Use Numba's register_jitable to avoid having to copy all the 'compute' functions.

- README.md
Dear vector developers,
this PR fixes the missing enclosing python highlighting "scope" of the python obj part in the README.md. I hope the position of the closing backticks is where you initially had them in mind :)
Best, Peter
> [README.md] markdown python highlighting 'scope' fix

- src/vector/_methods.py
- tests/test_methods.py
This PR addresses issue https://github.com/scikit-hep/vector/issues/127 by extending the [_handler_of](https://github.com/scikit-hep/vector/blob/5ba111555bae20887e417c1e73101a940d06fc57/src/vector/_methods.py#L2536-L2556) function to consider the module of all the inherited classes of a certain object. This is neccesary to allow the definition of client-side custom classes that can inherit from the library ones, and override their protocol methods (`__iadd__`, `__isub__` ...).
- I inverted the logic of the `if isinstance(obj, Vector)` to reduce indentation.
- I imported Python's `contextlib.suppress` helper to reduce indentation.
cc @jpivarski
> feat: allow overriding of protocol methods in subclasses

- src/vector/_backends/numba_object.py
- src/vector/_methods.py
- tests/backends/test_numba_object.py
Adds the following to 2D vectors:
* `scale2D`: same as `scale`
* `neg2D`: same as scaling/multiplying by `-1`
Adds the following to 3D vectors:
* `scale2D`: only scales the azimuthal components
* `scale3D`: same as `scale`
* `neg2D`: only negates the azimuthal components
* `neg3D`: same as scaling/multiplying by `-1`
Adds the following to 4D vectors:
* `scale2D`: only scales the azimuthal components
* `scale3D`: only scales the azimuthal and longitudinal components
* `scale4D`: same as `scale`
* `neg2D`: only negates the azimuthal components
* `neg3D`: only negates the azimuthal and longitudinal components
* `neg4D`: same as scaling/multiplying by `-1`
* `boostCM_of_p4(p4)`: boosts to the center-of-mass (CM) frame of `p4` (same as `boost_p4(p4.neg3D)`)
* `boostCM_of_beta3(beta3)`: boosts …
> Add boostCM_of to clarify #134, supported by scale*D and neg*D.

- README.md
It seems that `vector.arr` creates an `awkward` array, but the example code should create numpy arrays. This is a fix for the documentation about Numpy arrays of vectors.
> Fixed numpy array code examples in documentation

- src/vector/_backends/numpy_.py
- tests/backends/test_numpy.py
When sharing `VectorNumpy` based arrays (like `VectorNumpy3D`) between processes in python, [pickle](https://docs.python.org/3/library/pickle.html) is used for serialisation and deserialisation of the objects. But it seems that structured arrays which inherhit form a Numpy array lose part of their state during that process.
Here is an example that shows the problem:
```python
import pickle
import numpy as np
import vector
test = np.arange(0, 24, 0.1).view([("x", float), ("y", float), ("z", float)]).view(vector.VectorNumpy3D)
test_pickled = pickle.dumps(test)
test_new = pickle.loads(test_pickled)
print(test_new) # Leads to exception A
print(test_new[0]) # Leads to exception B
```
First, there is a problem that `__array_finalize__` is called twice from `pickle.loads`, once with the actual …
> VectorNumpy pickle suppport to enable multiprocessing

- README.md
I also rearranged a bit to follow the looks of the badges as in other packages.
> Add Conda and Zenodo badges to the README

- docs/api/vector._backends.rst
- docs/api/vector._compute.lorentz.rst
- docs/api/vector._compute.planar.rst
- docs/api/vector._compute.spatial.rst
- docs/api/vector._methods.rst
- docs/api/vector._typeutils.rst
- docs/api/vector.rst
- docs/api/vector.version.rst
- docs/index.rst
- docs/usage/intro.ipynb
- src/vector/_backends/__init__.py
- The intro notebook is currently broken because of missing extra `\`s when writing latex.
- There are no differences between `H2` and `H3` headings which makes the index in the documentation behave weirdly.
1. All the submodule headings are now `H3` and the headings saying "Submodule" are `H2`.
2. Vector's direct submodules have their independent `rst` files and pages now (The documentation for the submodules currently renders directly in the index page).
3. Added information about vector on the landing page.
4. Fixed the intro notebook.
**Current**
**New**
**Current**
**New**
**Current**
**New**
**Current**
**New**
**Current**
**New**
> docs: fix intro notebook, and submodule and subpackage index

- .github/dependabot.yml
- .github/workflows/ci.yml
- README.md
- docs/index.rst
- Currently, the conda badge points towards decay language
- Update `dependabot.yml` to catch next major versions
- Update `setup-python` with python version for `v4`
> chore: fix conda badge and update dependabot

- .github/CONTRIBUTING.md
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .pre-commit-config.yaml
- .readthedocs.yml
- MANIFEST.in
- README.md
- docs/changelog.md
- docs/index.rst
- environment.yml
- noxfile.py
- pyproject.toml
- setup.cfg
- src/vector/_methods.py
- src/vector/backends/_numba_object.py
- src/vector/backends/awkward.py
- src/vector/backends/numpy.py
- src/vector/backends/object.py
- Modifies `setup.cfg`, `.pre-commit-config.yaml`, and `pyproject.toml` to pass the repo review
- Adds `noxfile.py` for beginners
- Other changes are by the newly added pre-commit hooks
Repo review for this branch - https://scikit-hep.org/repo-review/?repo=Saransh-cpp%2Fvector&branch=saransh%2Frepo-review
(The red cross should ideally not appear since the dependabot check was fixed in the repo review repository. All the other green ticks are very satisfying to look at!)
> chore: pass repo review

- .github/codecov.yml
`Codecov` will now only respond once all 4 builds pass.
> chore: add `codecov.yml`

- .pre-commit-config.yaml
- pyproject.toml
Now that `vector` uses only `pyproject.toml` for specifying all the build and packaging-related things, I think adding this hook would be a good idea.
> chore: add `pyproject-fmt` pre-commit hook

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- docs/changelog.md
- src/vector/__init__.py
Currently, all the examples located in `vector`, as well as the introduction to constructors here - https://github.com/scikit-hep/vector#constructing-a-vector-or-an-array-of-vectors - point to the fact that `vector.arr` should construct `NumPy` vectors. This also seems logical (`Array` -> `awk` , `array` -> `arr`), and is most probably not wrong in the examples.
> fix: `vector.arr` should construct `NumPy` vectors

- .github/workflows/ci.yml
- .pre-commit-config.yaml
See https://github.com/python/mypy/issues/13627#issuecomment-1258470754
> chore: bump mypy and revert python-version

- docs/changelog.md
- pyproject.toml
- src/vector/_methods.py
- src/vector/backends/awkward.py
- src/vector/backends/numpy.py
- src/vector/backends/object.py
- tests/backends/test_object.py
- tests/compute/planar/test_deltaphi.py
- tests/compute/planar/test_phi.py
- tests/compute/planar/test_rho.py
- tests/compute/planar/test_rho2.py
- tests/compute/planar/test_rotateZ.py
- tests/compute/planar/test_x.py
- tests/compute/planar/test_y.py
- tests/compute/test_add.py
- tests/compute/test_dot.py
- tests/compute/test_equal.py
- tests/compute/test_isclose.py
- tests/compute/test_not_equal.py
- tests/compute/test_scale.py
- tests/compute/test_subtract.py
- tests/compute/test_unit.py
Closes #88.
WIP, currently just 2D Object implemented.
> feat: add constructors for `VectorObject2D` and `MomentumObject2D`

- .github/workflows/ci.yml
> chore: use Python 3.11!

- README.md
-------
While checking the available methods in the github readme I noticed that one $Delta$ didn't render properly as $\Delta$ so I decided to quickly fix add the missing backslash. On my fork this renders properly now. For testing I just ran pre-commit to check that I my editor didn't do any weird whitespace changes that I didn't notice. But I didn't run the unit tests or the doctests as I didn't change anything in the code. Should I?
> Fix missing backslash in latex for readme

- .flake8
- .github/ISSUE_TEMPLATE/bug_report.yml
> chore: ignore flake8 B905 + improve bug report template

- tests/test_compute_features.py
> fix: update discheck

- src/vector/backends/object.py
The `elif` condition missed checking for the `longitudinal` and `temporal` arguments.
> fix: better elif conditions for obj __init__ methods

- src/vector/_methods.py
> feat: update `to_Vector3D` to pass new coordinate values

- docs/changelog.md
- environment.yml
- pyproject.toml
- src/vector/backends/_numba_object.py
> chore: replace custom definition of np.isclose with numba's np.isclose

- .github/workflows/cd.yml
This moves publishing over to PyPI's trusted publishing. I'm adding this repo to PyPI now. (Edit: done)
> chore: use trusted publisher deployment

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- README.md
- docs/changelog.md
- docs/index.rst
- noxfile.py
- pyproject.toml
- src/vector/__init__.py
- src/vector/_typeutils.py
- tests/backends/test_awkward.py
Following https://github.com/scikit-hep/vector/pull/348#issuecomment-1557596467, this PR removes the support of Python 3.7 from vector. I'm still not completely sure if there was a concensus regarding this but I'll be happy to close this PR if we do want to support Python 3.7.
> chore: remove Python 3.7 support

- pyproject.toml
This is not following PEP 621, and we already have the canonical license classifier.
> chore: remove license string (not standard)

- src/vector/__init__.py
- src/vector/backends/numpy.py
- tests/backends/test_numpy.py
Fixes #372
See https://github.com/scikit-hep/vector/issues/372#issuecomment-1708622415
I've added tests for the default case as well.
> fix: `keepdims` in `numpy.sum` should not be `None`

- README.md
- docs/api/backends/vector.backends.awkward_constructors.rst
- docs/api/backends/vector.backends.rst
- docs/usage/intro.ipynb
- src/vector/backends/awkward.py
> docs: add docs for vector.zip

- README.md
- docs/changelog.md
- docs/usage/intro.ipynb
> Update `README` and `intro.ipynb` to include the latest developments

- .github/dependabot.yml
- pyproject.toml
- src/vector/backends/_numba_object.py
- src/vector/backends/awkward.py
- chore: touch up Ruff config
- chore: remove uneeded MyPy config line
- ci: grouped dependabot updates
I ran repo-review (below) and fixed most of the issues. The `warn_unreachable` one I think should probably check for existence, not the True setting.
See https://github.com/scientific-python/cookie/pull/348 for the grouping update.
<details>
<summary>Repo-review:</summary>
<h3>General</h3>
<ul>
<li>Detected build backend: <code>hatchling.build</code></li>
<li>Detected license(s): BSD License</li>
</ul>
<table>
<tr><th>?</th><th nowrap="nowrap">Name</th><th>Description</th></tr>
<tr style="color: green;">
<td><span role="img" aria-label="Passed">&#9989;</span></td>
<td nowrap="nowrap">PY001</td>
<td><a href="https://learn.scientific-python.org/development/guides/packaging-simple#PY001">Ha …
> chore: repo review updates

- README.md
- docs/usage/intro.ipynb
- src/vector/_methods.py
- src/vector/backends/awkward.py
- tests/backends/test_awkward.py
- tests/backends/test_numpy.py
- tests/backends/test_object.py
- tests/test_methods.py
Fixes #412
Output of the snippet attached in the issue:
```
a+b
[{x: 0, y: -20, z: 10}, {x: 40, y: 0, z: 0}, {x: 0, y: 60, z: 30}]
{'__record__': 'Momentum3D'}
b+a
[{x: 0, y: -20, z: 10}, {x: 40, y: 0, z: 0}, {x: 0, y: 60, z: 30}]
{'__record__': 'Momentum3D'}
```
> fix: vectors should be demoted to the lowest dimension

- src/vector/_methods.py
- tests/backends/test_awkward.py
- tests/test_methods.py
> feat: coordinate transformation functions with momentum names

- .github/workflows/notebooks.yml
- pyproject.toml
- src/vector/backends/awkward_constructors.py
- tests/backends/test_dask_awkward.py
> feat: add support for dask-awkward arrays in vector constructors

- README.md
- docs/usage/intro.ipynb
- src/vector/_methods.py
- tests/backends/test_awkward.py
- tests/compute/test_conversions.py
> feat: short names for to_VectorND methods

- src/vector/backends/awkward_constructors.py
> fix: support dask-awkward 2024.3.0

- src/vector/_methods.py
- src/vector/backends/awkward.py
- src/vector/backends/numpy.py
- src/vector/backends/object.py
- tests/backends/test_awkward.py
- tests/compute/test_conversions.py
> feat: make momentum-ness infectious

- noxfile.py
- src/vector/backends/awkward.py
- tests/backends/test_awkward.py
Closes #225 
Taking an example of coffee subclasses:
Before this PR:
```py
In [3]: a = ak.zip(
...:             {
...:                 "pt": [[1, 2], [], [3], [4]],
...:                 "eta": [[1.2, 1.4], [], [1.6], [3.4]],
...:                 "phi": [[0.3, 0.4], [], [0.5], [0.6]],
...:                 "energy": [[50, 51], [], [52], [60]],
...:             },
...:             with_name="PtEtaPhiELorentzVector",
...:             behavior=vector.behavior,
...:         )
In [4]: b = ak.zip(
...:             {
...:                 "rho": [10.0, 20.0, 30.0],
...:                 "theta": [0.3, 0.6, 1.1],
...:                 "phi": [-3.0, 1.1, 0.2],
...:             },
...:             with_name="SphericalThreeVector",
...:             behavior=vector.behavior,
...:         )
In [5]: …
```
> fix: momentum coords should not be repeated with generic coords in subclasses

- src/vector/backends/object.py
- tests/compute/test_isclose.py
- tests/test_issues.py
> fix: call the square implementation for power 2 on object vectors

- tests/compute/test_scale.py
> fix: use negfactor in negfactor scale test

- .github/workflows/cd.yml
* Add generation of GitHub artifact attestations to built sdist and wheel before upload. c.f.:
- https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/
- https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
* Add verification of artifact attestation before publishing vector to PyPI using the 'gh attestation verify' CLI API, added in v2.49.0.
- c.f. https://github.com/cli/cli/releases/tag/v2.49.0
```
* Add generation of GitHub artifact attestations to built sdist and wheel
before upload.
c.f.:
- https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/
- https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
* Add …
```
> ci: Add GitHub artifact attestations to package distribution

- src/vector/backends/numpy.py
- tests/test_issues.py
> fix: get coordinate classes to work for numpy

- docs/changelog.md
- pyproject.toml
- src/vector/backends/numpy.py
- src/vector/backends/object.py
- src/vector/backends/sympy.py
> fix: uncap numpy

- src/vector/backends/numpy.py
This PR adds descriptive example to the following properties in /src/vector/backends/numpy.py (Mentioned in #503)
- Azimuthal - 3D
- Azimuthal - 4D
- Longitudinal - 3D
- Longitudinal - 4D
The demo examples have been run and verified.
> Added examples for azimuthal and longitudinal properties in 3D and 4D

- .github/workflows/ci.yml
- noxfile.py
-------
Adds a nox session for disassemble tests as suggested on #532
Note that `--system` introduced in #511 was removed (unclear why that was needed).
> Adds a nox session for disassemble tests

- src/vector/backends/numpy.py
closes https://github.com/scikit-hep/vector/issues/503
> DOC: added an example for temporal property

- src/vector/backends/awkward.py
- tests/backends/test_dask_awkward.py
It is relevant to force touching of columns here, because it is not necessarily ensured that a `__getitem__` call, e.g. `arr["x"]` will add `x` to the typetracer report - but `x` is needed, otherwise the corresponding internal vector class can't be constructed.
> fix: typetracer 'under-touching'

- .github/CONTRIBUTING.md
Added missing quotation marks in `pip install -e` command
without `""`:
```
vector % pip install -e .[dev,test]  
zsh: no matches found: .[dev,test]
```
Also, I think, usually the new contributor's try to look for the `CONTRIBUTING.md` in the root directory. So, if there are no major consequences, I can move it from `.github` to the root directory and update all the links pointing to the contributor's guide accordingly, either in this PR or in a separate PR. Please LMK if this would be a helpful change.
Thank you :)
> Small fix in the contributor's guide

- src/vector/_methods.py
- src/vector/backends/awkward.py
- tests/backends/test_awkward.py
This PR fixes https://github.com/scikit-hep/coffea/pull/1195 (the current vector release 1.6.0 is broken for typetracers) 
The problem was that numpy (`lib`) functions were directly called on `TypeTracerArray`s. Instead, we should've used the corresponding `nplike` implementation if it exists. This is only implemented for the typetracer backend as all other backends have already a dedicated dispatch mechanism.
In order to ensure we're catching all errors with this I modified `tests/backend/test_awkward.py` to run every test also for the typetracer backend.
If this PR looks good and gets merged we should make a new release (and maybe yank the previous one?).
Sorry for the inconvenience!
(cc @lgray)
> fix: lib for typetracers

- docs/src/numba.ipynb
- pyproject.toml
This was requested in https://github.com/openjournals/joss-reviews/issues/7791#issuecomment-2688586263
> docs: better comparison between non-JIT and JIT in Numba notebook

- docs/index.md
Add metric, transformation and boost, and Euler angle conventions followed by vector (aligned with the ones followed in `ROOT` and `GenVector`).
See https://github.com/openjournals/joss-reviews/issues/7791#issuecomment-2692724384
> docs: add metric and transformation conventions

- pyproject.toml
Merged the last PR accidentally. I should have upper pinned python to 3.14 as numba releases are always (justifiably) late.
> Upper pin 3.14 for numba

- tests/compute/sympy/lorentz/test_deltaRapidityPhi.py
- tests/compute/sympy/lorentz/test_deltaRapidityPhi2.py
- tests/compute/sympy/lorentz/test_gamma.py
- tests/compute/sympy/lorentz/test_rapidity.py
- tests/compute/sympy/lorentz/test_t.py
- tests/compute/sympy/lorentz/test_t2.py
- tests/compute/sympy/lorentz/test_tau.py
- tests/compute/sympy/lorentz/test_tau2.py
- tests/compute/sympy/lorentz/test_to_beta3.py
resolves https://github.com/scikit-hep/vector/issues/579
<details>
<summary>Failure messages from CI :  https://github.com/scikit-hep/vector/actions/runs/14703378893 </summary>
```
=================================== FAILURES ===================================
_____________________________ test_lorentz_object ______________________________
def test_lorentz_object():
v1 = vector.MomentumSympy4D(
vector.backends.sympy.AzimuthalSympyXY(x, y),
vector.backends.sympy.LongitudinalSympyZ(z),
vector.backends.sympy.TemporalSympyTau(t),
)
v2 = vector.MomentumSympy4D( …
```
> fixing sympy tests  

- pyproject.toml
- src/vector/backends/awkward.py
- tests/test_issues.py
This PR fixes the handling of `lib` for non-NumPy and non-TypeTracer backends with awkward array.
fyi @MoAly98
> fix: correctly infer the numpy-like module

- docs/src/awkward.ipynb
Coming from https://github.com/scikit-hep/coffea/pull/1404
> docs: fix Record behavior in Awkward subclassing example

- docs/conf.py
The edit button right now does not work as our docs (like any typical python package) are not in the root directory but in the `docs` subdirectory.
> docs: fix edit button link

- .github/workflows/ci.yml
- CONTRIBUTING.md
- noxfile.py
- pyproject.toml
Dropping python 3.8, it's EOL.
> fix: drop python 3.8; it's EOL
