scikit-hep/vector

setup.py
Should remove a warning and work a bit better.
=> Bump Scikit-hep-testdata

.github/CONTRIBUTING.md, .gitignore, notebooks/VectorDesignPrototype.ipynb, src/vector/awkward/lorentz/__init__.py, src/vector/awkward/lorentz/xyzt.py, src/vector/common/lorentz/__init__.py, src/vector/common/lorentz/xyzt.py, src/vector/core/lorentz/xyzt.py, src/vector/numba/awkward/__init__.py, src/vector/numba/awkward/lorentz/__init__.py, src/vector/numba/awkward/lorentz/xyzt.py, src/vector/numba/lorentz/__init__.py, src/vector/numba/lorentz/xyzt.py, src/vector/numpy/lorentz/__init__.py, src/vector/numpy/lorentz/xyzt.py, src/vector/single/__init__.py, src/vector/single/lorentz/__init__.py, src/vector/single/lorentz/xyzt.py, tests/awkward_tests/test_demo.py, tests/conftest.py, tests/numba_tests/test_awkward.py, tests/numba_tests/test_basic.py, tests/root_tests/test_root_basic.py, tests/test_simple_numpy.py
This adds:
* More consistent folder structure.
* More consistent naming scheme.
* Basic pure-numpy support (not for Numba yet)
=> More structure

.github/workflows/ci.yml
Closes #10 when it works, follow up to #9.
=> Try built-in conda

README.md, environment.yml, setup.py, src/__init__.py, src/vector/__init__.py, src/vector/awkward/__init__.py, src/vector/awkward/lorentz/__init__.py, src/vector/awkward/lorentz/xyzt.py, src/vector/common/__init__.py, src/vector/common/lorentz/__init__.py, src/vector/common/lorentz/xyzt.py, src/vector/core/lorentz/__init__.py, src/vector/core/lorentz/all.py, src/vector/core/lorentz/xyzt.py, src/vector/numba/__init__.py, src/vector/numba/awkward/__init__.py, src/vector/numba/awkward/lorentz/__init__.py, src/vector/numba/awkward/lorentz/xyzt.py, src/vector/numba/lorentz/__init__.py, src/vector/numba/lorentz/xyzt.py, src/vector/numpy/lorentz/__init__.py, src/vector/numpy/lorentz/xyzt.py, src/vector/single/__init__.py, src/vector/single/lorentz/__init__.py, src/vector/single/lorentz/xyzt.py, tests/awkward_tests/test_demo.py, tests/numba_tests/test_awkward.py, tests/numba_tests/test_basic.py, tests/test_simple_numpy.py
Smaller update than expected, but better to get it in, then keep working.
=> Filling out a few more bits

.github/workflows/ci.yml, .pre-commit-config.yaml, setup.cfg, setup.py, src/vector/awkward/lorentz/xyzt.py, src/vector/core/lorentz/xyzt.py, src/vector/numba/lorentz/xyzt.py, src/vector/numpy/lorentz/xyzt.py, src/vector/protocols/lorentz.py, src/vector/single/lorentz/xyzt.py, tests/awkward_tests/test_demo.py, tests/awkward_tests/test_numba_basic.py, tests/numba_tests/test_awkward.py, tests/numba_tests/test_basic.py, tests/root_tests/test_root_basic.py, tests/test_simple_param.py
Updating formatting a bit in preparation for 2.7/3.5 being dropped #27.
=> chore: update formatting

.pre-commit-config.yaml, setup.cfg, src/vector/_backends/awkward_.py, src/vector/_backends/numpy_.py, src/vector/_backends/object_.py
Current failures if NumPy is installed (fixing VectorObject to support _SupportsArray will fix a batch of these):
```
src/vector/_backends/object_.py:185: error: Argument 1 to "__call__" of "ufunc" has incompatible type "VectorObject"; expected "Union[Union[int, float, complex, str, bytes, generic], Sequence[Union[int, float, complex, str, bytes, generic]], Sequence[Sequence[Any]], _SupportsArray]"
src/vector/_backends/object_.py:188: error: Argument 1 to "__call__" of "ufunc" has incompatible type "VectorObject"; expected "Union[Union[int, float, complex, str, bytes, generic], Sequence[Union[int, float, complex, str, bytes, generic]], Sequence[Sequence[Any]], _SupportsArray]"
src/vector/_backends/object_.py:191: error: Argument 1 to "__call__" of "ufunc" has incompatible type …
```
=> fix(types): support for external typing

src/vector/__init__.py, src/vector/_backends/numba_object.py, src/vector/_backends/numpy_.py, src/vector/_backends/object_.py, src/vector/_compute/lorentz/boost_beta3.py, src/vector/_compute/lorentz/boost_p4.py, tests/backends/test_numba_object.py, tests/compute/spatial/test_rotate_axis.py, tests/test_compute_features.py
Closes #56. Applying just the good changes from that PR, along with some cleanup.
=> style: partial application of sourcery.ai

src/vector/_backends/numpy_.py, src/vector/_backends/object_.py
Goodbye, 78 `type: ignores`. :)
=> fix(types): use static inheritance instead of dynamic

.github/dependabot.yml, .github/workflows/cd.yml, .github/workflows/ci.yml, README.md, setup.cfg
- ci: post release fixes
- docs: better links on PyPI
=> ci: fixes post release

.github/workflows/ci.yml, docs/changelog.md, setup.py, src/vector/__init__.py
Closes #75. There are other possible solutions, @jpivarski, if you prefer something different.
=> fix: cannot import without Awkward installed

setup.cfg, setup.py, src/vector/__init__.py, src/vector/_backends/awkward_.py
Closes #81.
Had a little trouble installing Awkward to test it (https://github.com/scikit-hep/awkward-1.0/issues/821), but seems to be working. Edit: fixed.
=> fix: check awkward version

docs/conf.py, setup.py
CC https://github.com/readthedocs/recommonmark/issues/221
=> docs: convert recommonmark to myst-parser

.pre-commit-config.yaml, README.md, docs/index.rst, pyproject.toml, setup.cfg, src/vector/_backends/awkward_constructors.py
- chore: adding a few more checks
- chore: move quite a bit of config to using TOML
=> chore: pre-commit and style cleanup

README.md, docs/api/vector._compute.lorentz.rst, docs/usage/intro.ipynb, tests/compute/lorentz/test_deltaRapidityPhi.py, tests/compute/lorentz/test_deltaRapidityPhi2.py
Reopening PR after rebasing to main per discussion [here](https://github.com/scikit-hep/vector/pull/175#issuecomment-1106602474)
=> Tests and docs for deltaRapidityPhi

src/vector/backends/awkward.py
Added docstrings and minor examples!
=> docs: add docstrings in the `backends.awkward` module

.github/workflows/ci.yml, setup.py, src/vector/backends/awkward.py, src/vector/backends/numpy.py, src/vector/backends/object.py
Closes #208 
- Add `xdoctests` to `test` dependepncies
- Fix the already written doctests and make them deterministic
- Run doctests in the CI
=> Implement doctests in CI

src/vector/backends/awkward.py
Closes #209 
- Add custom `__repr__` methods
- Update the doctests to reflect the same
=> Add custom reprs to awkward coordinate classes

.git_archival.txt, .gitattributes
Updates `vector` with the new versioning feature (or bug fix?) mentioned here - https://github.com/scikit-hep/scikit-hep.github.io/pull/250
=> feat: add git archive support

docs/changelog.md
For previous versions and for `v0.9.0`.
=> docs: update changelog

.github/workflows/ci.yml, docs/changelog.md, noxfile.py, pyproject.toml
=> chore: test on `awkard v1.10.0` and add cov to `noxfile`

.flake8, .github/matchers/pylint.json, .github/workflows/ci.yml, .pre-commit-config.yaml, docs/usage/intro.ipynb, docs/usage/vector_design_prototype.ipynb, noxfile.py, pyproject.toml, src/vector/__init__.py, src/vector/_compute/lorentz/__init__.py, src/vector/_compute/planar/__init__.py, src/vector/_compute/spatial/__init__.py, src/vector/backends/_numba.py, src/vector/backends/_numba_object.py, src/vector/backends/awkward.py, src/vector/backends/awkward_constructors.py, src/vector/backends/numpy.py, src/vector/backends/object.py, tests/compute/test_unit.py
=> Add PyLint and additional pre-commit hooks

.github/workflows/ci.yml
See https://github.com/python/mypy/issues/13627
=> Fix the failing mypy hook by pinning python-version

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, docs/changelog.md
- The changelog was outdated (we should try updating it with every PR)
- Minor typo in PR template
- Add documentation for `nox -s notebooks`
=> docs: update changelog.md, PR template, and CONTRIBUTING.md

docs/changelog.md
=> Update changelog - prepare for v0.11.0

.pre-commit-config.yaml, src/vector/backends/numpy.py, src/vector/backends/object.py
Xref: https://github.com/scikit-hep/vector/pull/306#issuecomment-1386105128
=> ci: use numpy~=1.24.0 in pre-commit

.github/codecov.yml
=> ci: update number of builds for codecov bot

docs/changelog.md
Also sets up the changelog for v1
=> docs: a readable changelog

docs/changelog.md
=> CHANGELOG for v1.1.0

.gitignore, docs/api/vector.rst, docs/api/vector.version.rst, docs/changelog.md, docs/conf.py, pyproject.toml, src/vector/__init__.py
=> chore: clean up VCS versioning

README.md, docs/index.rst
Updated the github actions badge in docs
Fixes #383
=> Fix CI badge in README and docs

src/vector/backends/awkward.py, src/vector/backends/numpy.py, src/vector/backends/object.py
=> Fix Vector* mixin's docstring

.pre-commit-config.yaml, pyproject.toml, src/vector/_compute/spatial/is_antiparallel.py, src/vector/_compute/spatial/is_parallel.py, src/vector/_compute/spatial/is_perpendicular.py, src/vector/backends/numpy.py, src/vector/backends/object.py, tests/backends/test_operators.py
=> black -> ruff format

docs/changelog.md
=> docs: update changelog for v1.2

.github/workflows/ci.yml
=> chore: test on numpy 2.0

tests/compute/lorentz/test_is_lightlike.py, tests/compute/lorentz/test_is_spacelike.py, tests/compute/lorentz/test_is_timelike.py, tests/compute/test_is_antiparallel.py, tests/compute/test_is_parallel.py, tests/compute/test_is_perpendicular.py
=> chore: add missing compute function tests

.pre-commit-config.yaml, tests/compute/sympy/test_scale.py
=> fix: sympy backend on numpy 2.0 (full numpy 2.0 support)

src/vector/_compute/spatial/deltaangle.py, src/vector/_lib.py, tests/test_compute_features.py, tests/test_issues.py
=> fix: add lower and upper bounds for deltaangle

docs/changelog.md
=> prepare for v1.4.1

.github/workflows/ci.yml
=> chore: fix ci for awkward v1.x (numpy v2 is out)

noxfile.py, tests/compute/sympy/lorentz/test_Et.py, tests/compute/sympy/lorentz/test_Et2.py, tests/compute/sympy/lorentz/test_beta.py, tests/compute/sympy/test_unit.py
=> fix: sympy tests (sympy v1.13)

docs/changelog.md
=> chore: prepare for v1.4.2 (last release before dropping awkward v1)

.github/workflows/ci.yml
- [#] Have you followed the guidelines in our Contributing document?
- [#] Have you checked to ensure there aren't any other open Pull Requests for the required change?
- [#] Does your submission pass pre-commit? (`$ pre-commit run --all-files` or `$ nox -s lint`)
- [#] Does your submission pass tests? (`$ pytest` or `$ nox -s tests`)
- [#] Does the documentation build with your changes? (`$ cd docs; make clean; make html` or `$ nox -s docs`)
- [#] Does your submission pass the doctests? (`$ pytest --doctest-plus src/vector/` or `$ nox -s doctests`)
- [#] …
=> Remove occurrences of matrix.python-version.key || in ci.yml

README.md, docs/index.rst
=> Add CHEP and PyHEP talks

CITATION.cff
=> Update Saransh's affiliation

paper/paper.bib, paper/paper.md
Makes some typographic edits in JOSS paper
=> Updates JOSS paper

pyproject.toml
=> SymPy listed twice as a dev dependency

CONTRIBUTING.md
=> docs: move and update contributing guide
